### ISSUE TITLE
Missing stroke number Garmin 

### ISSUE THREAD

**Issue by TbsJah** [svenmeier/coxswain#69]
Garmin does not shows the stroke number
Maybe it is a tcx problem

**Comment by svenmeier** [comment]
Coxswain exports strokes as steps in a TCX extension:

```
<Extensions>
<LX xmlns="http://www.garmin.com/xmlschemas/ActivityExtension/v2">
<Steps>898</Steps>
</LX>
</Extensions>
```

I don't know why Garmin doesn't accept these :(

**Comment by Joe4ro** [comment]
On my Pixel XL running Android 8.1 it only shows the count down timer. All other data stays at all zeros. I un-installed and re installed the app. Same issue. This started after the update.

**Comment by svenmeier** [comment]
@Joe4ro "All other data stays at all zeros"

Are you referring to the Garmin tcx export or a general problem with the workout display?

**Comment by Joe4ro** [comment]
No. I plug my Pixel XL phone with a USB C on the go cable. I plug it into the back of the S4 Monitor. Everything worked great until i updated the app version 4.9.  It will show the countdown timer, but all other data stays at 000.













---- On Mon, 11 Dec 2017 11:49:32 -0500 Sven Meier &lt;notifications@github.com&gt; wrote ----




@Joe4ro "All other data stays at all zeros"

Are you referring to the Garmin tcx export or a general problem with the workout display?

**Comment by TbsJah** [comment]
4.9 working fine for me (s8)
Please delete data and cache. That was the solution for me

**Comment by svenmeier** [comment]
@joe4ro please open a new ticket if the problem persists, thanks.

**Comment by j-rowe** [comment]
Hoping to resurrect this issue.  Having the .tcx files import to garmin correctly would be the final touch to this great app.  Currently when I upload they get classified as a ride with some random straightline GPS coordinates and the strokes saved as steps.  If the files could either be generated correctly or to use the garmin api (wishful thinking probably!) that would be wonderful.  Sorry, I'm not a coder or would try and help more...

**Comment by svenmeier** [comment]
Garmin keeps steps in their .tcx files in the exact same format:

http://developer.garmin.com/downloads/connect-api/sample_file.tcx

**Comment by j-rowe** [comment]
Thanks for replying but if we are uploading can the file from coxswain not tell Garmin that this is an indoor row rather than a ride? Then surely it will apply the fields correctly?

**Comment by svenmeier** [comment]
Sorry, but I don't have time to sort out this problem. It doesn't seem like Garmin is really interested in interoperability with other apps.

What you can do: Take your .tcx file to Garmin and ask them what's wrong with it.
Perhaps this issue has been solved by someone else already. I assume you are already registered, so you could ask on that forum thread I linked above.

**Comment by foxytop** [comment]
I believe this is an issue because garmin does not view the activity as a row.  The activity type needs to be updated to "indoor rowing".  When I import the tcx into garmin the activity type automatically shows as "other".

**Comment by inonoob** [comment]
To recap: 

Problem: Garmin connect is not showing strokes for indoor rowing. Despite the fact that the TCX file developed by Garmin and used in Coxswain has been structures as required by Garmin it is still not working. [link](https://en.wikipedia.org/wiki/Training_Center_XML)

Proposed solution: Implement the new Garmin format "FIT" file. Which is a binary format of an activity [link](https://developer.garmin.com/fit/file-types/activity/=) 
So Coxswain should take the data from the gym database, encode them according to the FIT file specs and export them in order to have the best Garmin connect integration. 
The SDK and all the information can be download from here: [link](https://developer.garmin.com/fit/download/) 

Background: in the early days of smartwatch and date gathering for sport activities, Garmin developed the program  Garmin Training Center [link](https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fd2.alternativeto.net%2Fdist%2Fs%2Fb8b8b018-8194-e211-845a-0025902c7e73_4_full.jpg%3Fformat%3Djpg%26width%3D1600%26height%3D1600%26mode%3Dmin%26upscale%3Dfalse&f=1&nofb=1) and along with the program the exchange file Training Center XML (TCX) has been developed. This file format has only 3 categories for sport : ( Running, Bike and Others). 
Years passed by and then the Cloud revolution begun everything had to be in the cloud and smartwatches became more and more a thing. So Cloud + IoT = new era. 
Garmin decide to introduce a new format which is called the FIT format. Which has a lot more information and can be used for a lot of fitness IoT devices. Rowing machine, Smartscales and the list goes on. 
This new file is a binary file which has all the information needed. An example is each sport has an dedicated number. But also a lot of other things can be stored in that file. The Waterrower for example has the manufacture id 118 so it exist but not yet used. 
Garmin connect is complete centered and focused on the FIT file system. The TCX format is a legacy format which is still used as it is widely adopted for a lot of fitness tracking pages, apps and fitness machines. 
I should mention that the FIT format is proprietary to Garmin.
